/**
 * The icon font is generated by hand and committed (see `scripts/build-icon-font.py`), so the
 * one thing that can silently rot is drift between the glyphs the component names and the
 * glyphs the subset actually holds: a codepoint added to `Icon.astro` alone renders as a
 * blank box on the page, and nothing else complains.
 *
 * The generator already proves each codepoint against the upstream font's cmap before it
 * writes the subset, so keeping the two lists identical is enough to keep the shipped font
 * correct. Reading the cmap back out of the committed woff2 would mean a Brotli-and-table
 * parser here for no additional guarantee.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const component = readFileSync('src/components/Icon.astro', 'utf8');
const generator = readFileSync('scripts/build-icon-font.py', 'utf8');

/** `'open-in-new': '\ue89e',` → 0xe89e */
const componentCodepoints = [...component.matchAll(/'[a-z0-9-]+':\s*'\\u([0-9a-f]{4})'/g)].map((m) =>
  Number.parseInt(m[1], 16),
);

/** `"open_in_new": 0xE89E,` → 0xe89e */
const generatorCodepoints = [...generator.matchAll(/"[a-z0-9_]+":\s*0x([0-9A-F]{4})/g)].map((m) =>
  Number.parseInt(m[1], 16),
);

test('the component names at least one glyph', () => {
  assert.ok(componentCodepoints.length > 0, 'no glyphs parsed out of Icon.astro — has GLYPHS changed shape?');
});

test('every glyph the component names is in the generated subset', () => {
  assert.deepEqual(
    componentCodepoints.toSorted(),
    generatorCodepoints.toSorted(),
    'Icon.astro and scripts/build-icon-font.py disagree: regenerate the font after changing either',
  );
});

test('the subset font is committed and is a woff2', () => {
  const font = readFileSync('src/styles/fonts/material-symbols-rounded-subset.woff2');
  assert.equal(font.subarray(0, 4).toString('latin1'), 'wOF2');
  assert.ok(font.length < 8 * 1024, `the subset is ${font.length} bytes — a full Material Symbols cut leaked in`);
});
